name: Flutter CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Verify dependencies
      run: flutter pub deps
    - name: Analyze project source
      run: flutter analyze
    - name: Run tests
      run: flutter test
    - name: Build web
      run: flutter build web
    - name: Build Android APK
      run: flutter build apk --debug

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Build Web
      run: flutter build web
    - name: Deploy
      run: |
        cd build/web
        git init
        git config user.name  "CI"
        git config user.email "flutter-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/zonble/flutter_animation_slide.git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated docs"
        git push --force secure-origin gh-pages